name: CI-Build-Pipeline
on:
  push:
    branches:
      - main # Or any branch you want to trigger this action
  pull_request:
    branches:
      - main # Optional: For pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest # Or 'windows-latest' if you prefer running on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '6.5.0'
    

    - name: Restore NuGet packages
      run:  nuget restore $(find . -name "*.sln")

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2

    - name: Define Artifact Staging Directory
      run: echo "ARTIFACT_STAGING_DIR=${{ github.workspace }}\artifacts" >> $GITHUB_ENV

    - name: Build with MSBuild
      shell: pwsh
      run: |
        $solution = "MyMvcApp.sln"
        $packageLocation = "${{ env.ARTIFACT_STAGING_DIR }}"
        & msbuild $solution `
          /p:PackageLocation="$packageLocation" `
          /p:DeployOnBuild=True `
          /p:CleanIntermediateFilesAfterBuild=true `
          /v:q /maxcpucount `
          /p:Configuration=Release `
          /p:Platform="Any CPU"
        
    - name: Publish Artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: drop-${{ github.run_number }}
        path: ${{ github.workspace }}

    - name: Publish Symbols for Main Branch
      uses: actions/upload-artifact@v4
      with:
        name: symbols
        path: '**/bin/**/*.pdb'

    
        
