name: CI-Build-Pipeline
on:
  push:
    branches:
      - main # Or any branch you want to trigger this action
  pull_request:
    branches:
      - main # Optional: For pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest # Or 'windows-latest' if you prefer running on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NuGet
      uses: NuGet/NuGetAction@v2
      with:
        nuget-version: '6.5.0'

    - name: Restore NuGet packages
      run: nuget restore '*.sln;Build.proj' -Source 'https://nuget.org/api/v2'

    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2

    - name: Execute Build
      run: |
        msbuild Build.proj /p:PackageLocation="$(System.ArtifactStagingDirectory)\\" /p:DeployOnBuild=True /p:CleanIntermediateFilesAfterBuild=true /v:q /maxcpucount /p:Configuration=$(BuildConfiguration) /p:Platform=$(BuildPlatform)
      env:
        BuildConfiguration: 'Release'  # Set as per your requirement
        BuildPlatform: 'x64'  # Set as per your requirement
    - name: Publish Artifacts
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: $(System.DefaultWorkingDirectory)
    - name: Publish Symbols for Main Branch
      uses: actions/upload-artifact@v3
      with:
        name: symbols
        path: '**/bin/**/*.pdb'
    
        
