name: Dev Web Apps Deploy 

on:
  push:
    branches:
      - dev/1971-Set-Up-a-New-GitHub-Actions
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev1'
        type: choice
        options:
          - dev1
          - dev2
          - dev3
          - dev4
          - qa
      build-number:
        description: 'The build number to deploy'
        required: true

jobs:
  download-artifacts:
    runs-on: windows-latest
    steps:
      - name: Check if artifact exists by name
        run: |
          artifact_name="drop-${{ github.event.inputs.build-number }}"
          echo "Checking for artifact: $artifact_name"
      
          # List all artifacts for the repository and filter by name
          artifact_id=$(gh api -H "Accept: application/vnd.github.v3+json" \
            /repos/amanrio/NetCore-Automation-Test/actions/artifacts \
            | jq -r ".artifacts[] | select(.name == \"$artifact_name\") | .id")
      
          if [ -z "$artifact_id" ]; then
            echo "Artifact $artifact_name not found!"
            exit 1
          else
            echo "Artifact $artifact_name found with ID: $artifact_id"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: drop-${{ github.event.inputs. build-number}}
          path: ./drop
          
         

      - name: Upload artifacts for later use
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artifacts
          path: drop/

  deploy:
    needs: download-artifacts
    runs-on: windows-latest
    strategy:
      matrix:
        environment: [ "${{ github.event.inputs.environment || 'dev1' }}" ]
        app:
          - { name: "keystone-api", artifact: "keystone.web.api.zip" }
          - { name: "keystone-auth", artifact: "Keystone.Web.Auth.zip" }
          - { name: "keystone-callback", artifact: "Keystone.Web.Callback.zip" }
          - { name: "keystone-api-autotask", artifact: "Keystone.Web.Api.Autotask.zip" }
          - { name: "keystone-externalredirect", artifact: "Keystone.Web.ExternalRedirect.zip" }
          - { name: "keystone-emailscheduler", artifact: "Keystone.Web.EmailScheduler.zip" }
          - { name: "keystone-image", artifact: "Keystone.Web.Images.zip" }
          - { name: "keystone-productimporter", artifact: "Keystone.Web.ProductImporter.zip" }
          - { name: "keystone-provision", artifact: "Keystone.Web.Provision.zip" }
          - { name: "keystone-scheduler", artifact: "Keystone.Web.Scheduler.zip" }
          - { name: "keystone-jobscheduler", artifact: "Keystone.Web.JobScheduler.zip" }
          - { name: "keystone-support-portal", artifact: "Keystone.Web.BackOffice.zip" }

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy-artifacts
          path: drop

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: keystone-${{ matrix.environment }}-${{ matrix.app.name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: drop/${{ matrix.app.artifact }}
