name: Deploy Web Apps (Matrix Deployment)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (dev1, dev2, prod)'
        required: true
        type: choice
        options:
          - dev1
          - dev2
          - dev3
          - dev4
          - qa1
          - prod
      run_id:
        description: 'Enter the Workflow Run ID (leave empty for latest)'
        required: true
        type: string
        default: 'latest'  # Default value

jobs:
  get_run_id:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.get_run_id_output.outputs.run_id }}

    steps:
      - name: Get Latest Successful Run ID for Build Workflow (If "latest" is selected)
        id: get_run_id_output
        run: |
          if [ "${{ github.event.inputs.run_id }}" == "latest" ]; then
            echo "Fetching the latest successful workflow run ID for the build workflow..."
            run_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/buildpublish.yml/runs?status=success&per_page=1" \
              | jq -r '.workflow_runs[0].id')
            
            # Check if run_id is valid
            if [ "$run_id" != "null" ]; then
              echo "Latest Run ID: $run_id"
              echo "::set-output name=run_id::$run_id"
            else
              echo "No successful workflow runs found."
              exit 1
            fi
          else
            echo "Using provided run_id: ${{ github.event.inputs.run_id }}"
            echo "::set-output name=run_id::${{ github.event.inputs.run_id }}"
          fi

  deploy:
    needs: get_run_id
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }} 
    strategy:
      matrix:
        include:
          - app_name: keystone-api-01
            artifact_name: keystone.web.api
          - app_name: keystone-api-autotask-01
            artifact_name: keystone.web.api-autotask
          - app_name: keystone-api-dattopsa-01
            artifact_name: keystone.web.api-dattopsa
          - app_name: keystone-auth-01
            artifact_name: keystone.web.auth
          - app_name: keystone-scheduler-01
            artifact_name: keystone.web.scheduler

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts from Previous Workflow
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.get_run_id.outputs.run_id }}  # Using dynamically fetched run ID
          artifact-name: ${{ matrix.artifact_name }}
          path: ./artifact/drop

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ${{ github.event.inputs.environment }}  Environment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ matrix.app_name }}
          resource-group: myResourceGroup
          slot-name: 'production'
          environment: ${{ github.event.inputs.environment }} 

      - name: Logout of Azure
        run: az logout
