name: Deploy Web Apps (Matrix Deployment)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (dev1, dev2, prod)'
        required: true
        type: choice
        options:
          - dev1
          - dev2
          - dev3
          - dev4
          - qa1
          - prod
      run_id:
        description: 'Select the Workflow Run ID'
        required: true
        type: choice
        default: 'latest'  # This will be populated dynamically in the next steps

jobs:
  get_run_ids:
    runs-on: ubuntu-latest
    outputs:
      run_ids: ${{ steps.set_run_ids.outputs.run_ids }}

    steps:
    - name: Set Run IDs
      id: set_run_ids
      run: |
        # Fetch the list of previous workflow runs using GitHub API
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
          | jq '.workflow_runs | map(select(.status == "success")) | .[:5] | map(.id)' > run_ids.json
        
        # Read the run IDs and print them
        echo "Run IDs: $(cat run_ids.json)"
        
        # Set the output for GitHub Actions to use later
        echo "::set-output name=run_ids::$(cat run_ids.json)"
    
  deploy:
    needs: get_run_ids
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app_name: keystone-api-01
            artifact_name: keystone.web.api
          - app_name: keystone-api-autotask-01
            artifact_name: keystone.web.api-autotask
          - app_name: keystone-api-dattopsa-01
            artifact_name: keystone.web.api-dattopsa
          - app_name: keystone-auth-01
            artifact_name: keystone.web.auth
          - app_name: keystone-scheduler-01
            artifact_name: keystone.web.scheduler

    steps:
      - name: Checkout Repository (if needed)
        uses: actions/checkout@v3

      - name: Download Build Artifacts from Previous Workflow
        uses: actions/download-artifact@v2
        with:
          run-id: ${{ github.event.inputs.run_id }}  # Dynamic run ID input
          artifact-name: drop  # The artifact name per matrix
          path: ./artifact/drop

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Web App
        run: |
          zip_file="./artifact/drop/drop.zip"
          az webapp deployment source config-zip --resource-group myResourceGroup --name "${{ matrix.app_name }}" --src "$zip_file"

      - name: Logout of Azure
        run: az logout
