name: Deploy Web Apps (Matrix Deployment)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy (dev1, dev2, prod)'
        required: true
        type: choice
        options:
          - dev1
          - dev2
          - dev3
          - dev4
          - qa1
          - prod
      # release_version:
      #   description: 'Enter the release version (e.g., latest or specific build number)'
      #   required: true
      #   default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app_name: keystone-api-01
            artifact_name: keystone.web.api
          - app_name: keystone-api-autotask-01
            artifact_name: keystone.web.api-autotask
          - app_name: keystone-api-dattopsa-01
            artifact_name: keystone.web.api-dattopsa
          - app_name: keystone-auth-01
            artifact_name: keystone.web.auth
          - app_name: keystone-scheduler-01
            artifact_name: keystone.web.scheduler
    steps:
      - name: Checkout Repository (if needed)
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        run: |
          mkdir -p artifact/drop
          cp $(System.DefaultWorkingDirectory)/artifact/drop/${{ matrix.artifact_name }}.zip artifact/drop/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Web App
        run: |
          zip_file="artifact/drop/${{ matrix.artifact_name }}.zip"
          az webapp deployment source config-zip --resource-group myResourceGroup --name "${{ matrix.app_name }}" --src "$zip_file"

      - name: Logout of Azure
        run: az logout
